const fs = require('fs');
const path = require('path');

const DATABASE_MD_FILE = path.join(__dirname, 'contacts_database.md');
const BATCHES_FILE = path.join(__dirname, 'ingestion_batches_database.json');
const BACKUP_DIR = path.join('C:', 'Users', 'Ubu', '.gemini', 'antigravity', 'KANNEM CRM', 'Contacts');

// Data set from Agent 2 (States NE to WY)
const agent2Data = [
  {
    "recordId": "REC-NE-01",
    "firstName": "Dennis",
    "lastName": "Whitfield",
    "companyName": "DWS Services",
    "position": "Founder & Principal Land Surveyor",
    "email": "dws-services@cox.net",
    "phone": "(402) 292-1221",
    "stateRegion": "Nebraska",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Established in 1983; specializes in residential boundary surveys, lot surveys, ALTA surveys, and construction management across Omaha and Bellevue, NE.",
    "websiteUrl": "https://dws-landsurveyor.com"
  },
  {
    "recordId": "REC-NV-01",
    "firstName": "Randy",
    "lastName": "Meyer",
    "companyName": "Meyer Surveying",
    "position": "Owner & Principal Surveyor",
    "email": "rmeyer@meyersurvey.com",
    "phone": "(775) 786-1166",
    "stateRegion": "Nevada",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Over 20 years of experience; provides boundary, topographic, construction staking, and FEMA elevation certificate services across Reno and northern Nevada.",
    "websiteUrl": "http://www.meyersurvey.com"
  },
  {
    "recordId": "REC-NH-01",
    "firstName": "Scott",
    "lastName": "Frankiewicz",
    "companyName": "NH Land Consultants, LLC",
    "position": "Owner & Founder",
    "email": "scott@nhlandconsultants.com",
    "phone": "(603) 833-5913",
    "stateRegion": "New Hampshire",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Over 35 years of experience in land surveying, septic design, and land planning; licensed land surveyor in New Hampshire based in Northwood.",
    "websiteUrl": "https://nhlandconsultants.com"
  },
  {
    "recordId": "REC-NJ-01",
    "firstName": "Greg",
    "lastName": "Schwerzler",
    "companyName": "Schwerzler Land Surveying",
    "position": "Owner & Licensed Land Surveyor",
    "email": "greg@schwerzlerland.com",
    "phone": "(201) 660-8375",
    "stateRegion": "New Jersey",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Based in Elmwood Park; provides boundary surveys, ALTA surveys, drone aerial mapping, and elevation certificates throughout New Jersey.",
    "websiteUrl": "https://schwerzlerland.com"
  },
  {
    "recordId": "REC-NM-01",
    "firstName": "Lee",
    "lastName": "Shields",
    "companyName": "Shields Survey Ltd. Co.",
    "position": "Principal & Licensed Professional Surveyor",
    "email": "lee@shieldssurvey.com",
    "phone": "(575) 445-1232",
    "stateRegion": "New Mexico",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Established in 1972; provides boundary, GPS, right-of-way, ALTA/ACSM, and subdivision surveying services across New Mexico.",
    "websiteUrl": "http://www.shieldssurvey.com"
  },
  {
    "recordId": "REC-NY-01",
    "firstName": "Kyle",
    "lastName": "Mott",
    "companyName": "Mott Land Surveying",
    "position": "Principal & Licensed Land Surveyor",
    "email": "Kmott@MottLS.com",
    "phone": "(585) 514-4204",
    "stateRegion": "New York",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Specializes in Finger Lakes region; offers boundary surveys, subdivisions, ALTA/NSPS surveys, topographic mapping, and drone surveying.",
    "websiteUrl": "https://mottls.com"
  },
  {
    "recordId": "REC-NC-01",
    "firstName": "David",
    "lastName": "Skidmore",
    "companyName": "Skidmore Surveying, Inc.",
    "position": "President & Professional Land Surveyor",
    "email": "david@skidmoresurveying.com",
    "phone": "(704) 289-4855",
    "stateRegion": "North Carolina",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Based in Monroe; provides residential boundary surveys, physical surveys, and ALTA surveys for Union, Mecklenburg, and Cabarrus counties.",
    "websiteUrl": "https://skidmoresurveying.com"
  },
  {
    "recordId": "REC-ND-01",
    "firstName": "KC",
    "lastName": "Homiston",
    "companyName": "Highlands Engineering & Surveying, PLLC",
    "position": "President & Principal Surveyor",
    "email": "Homiston@Highlandseng.com",
    "phone": "(701) 483-2444",
    "stateRegion": "North Dakota",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Dickinson-based engineering and land surveying firm offering boundary surveys, construction layout, ALTA surveys, and infrastructure mapping.",
    "websiteUrl": "https://www.highlandsengineering.com"
  },
  {
    "recordId": "REC-OH-01",
    "firstName": "Kyle",
    "lastName": "Binkley",
    "companyName": "Binkley Land Surveying, LLC",
    "position": "Owner & Professional Surveyor",
    "email": "kyle@binkleylandsurveying.com",
    "phone": "(419) 738-8413",
    "stateRegion": "Ohio",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Founded in 2013; based in Wapakoneta; provides boundary surveys, construction staking, ALTA surveys, and FEMA floodplain analysis across western Ohio.",
    "websiteUrl": "https://binkleylandsurveying.com"
  },
  {
    "recordId": "REC-OK-01",
    "firstName": "Micah",
    "lastName": "Gustin",
    "companyName": "Gustin Land Surveying, LLC",
    "position": "Owner & Professional Land Surveyor",
    "email": "micah@gustinlandsurveying.com",
    "phone": "(405) 740-6748",
    "stateRegion": "Oklahoma",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Based in Oklahoma City; provides boundary surveys, ALTA/NSPS land title surveys, topographic surveys, and construction staking across Oklahoma.",
    "websiteUrl": "https://www.gustinlandsurveying.com"
  },
  {
    "recordId": "REC-OR-01",
    "firstName": "Drew",
    "lastName": "Johnston",
    "companyName": "TerraTech Land Surveyors, LLC",
    "position": "Owner & Principal Land Surveyor",
    "email": "Drew@terratechlandsurveyors.com",
    "phone": "(458) 278-5932",
    "stateRegion": "Oregon",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Located in Lebanon, OR; provides boundary surveys, ALTA/NSPS surveys, partition plats, drone LiDAR, and construction layout across the Willamette Valley.",
    "websiteUrl": "https://terratechlandsurveyors.com"
  },
  {
    "recordId": "REC-PA-01",
    "firstName": "Michael",
    "lastName": "Bieber",
    "companyName": "Bieber Land Surveying Company, LLC",
    "position": "President & Professional Land Surveyor",
    "email": "mbieber@bieblsc.com",
    "phone": "(484) 824-8991",
    "stateRegion": "Pennsylvania",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Over 30 years experience; based in Lionville; serves southeastern PA with ALTA/ACSM land title surveys, boundary surveys, and construction layout.",
    "websiteUrl": "https://bieblsc.com"
  },
  {
    "recordId": "REC-RI-01",
    "firstName": "Eric",
    "lastName": "Colburn",
    "companyName": "Foster Survey Company",
    "position": "President & Co-Founder",
    "email": "ecolburn@fostersurvey.com",
    "phone": "(401) 647-9240",
    "stateRegion": "Rhode Island",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Established full-service surveying company based in Foster/Cranston, RI; specializes in boundary surveys, GPS, subdivisions, and site development.",
    "websiteUrl": "https://fostersurvey.com"
  },
  {
    "recordId": "REC-SC-01",
    "firstName": "Lloyd",
    "lastName": "Lucas",
    "companyName": "Lucas Land Surveying, LLC",
    "position": "Owner & President",
    "email": "lloyd@lucaslandsurveying.com",
    "phone": "(803) 924-8755",
    "stateRegion": "South Carolina",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Based in Little Mountain; licensed since 2004; provides boundary surveys, ALTA/NSPS surveys, construction staking, and topographic surveys across SC Midlands.",
    "websiteUrl": "https://lucaslandsurveying.com"
  },
  {
    "recordId": "REC-SD-01",
    "firstName": "Marty",
    "lastName": "Mack",
    "companyName": "Mack Land Surveying",
    "position": "Owner & Registered Land Surveyor",
    "email": "macklandsurveying@gmail.com",
    "phone": "(605) 878-2007",
    "stateRegion": "South Dakota",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Established in 2012 in Watertown, SD; Registered Land Surveyor and Certified Federal Surveyor (CFEDS) providing boundary surveys, mortgage surveys, and platting.",
    "websiteUrl": "https://macklandsurveying.com"
  },
  {
    "recordId": "REC-TN-01",
    "firstName": "Don",
    "lastName": "VanHook",
    "companyName": "Cataska Land Surveying",
    "position": "Owner & Professional Land Surveyor",
    "email": "cataska2745@outlook.com",
    "phone": "(423) 292-0174",
    "stateRegion": "Tennessee",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Operated by former TDOT CE Manager Don VanHook Jr.; over 35 years experience; serves Polk and Bradley counties with comprehensive land surveying services.",
    "websiteUrl": "https://cataskalandsurveying.com"
  },
  {
    "recordId": "REC-TX-01",
    "firstName": "Roberto",
    "lastName": "Cardenas",
    "companyName": "Texas Geo Tech Land Surveying, Inc.",
    "position": "President",
    "email": "roberto@texasgeotech.com",
    "phone": "(361) 993-0808",
    "stateRegion": "Texas",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Founded in 2000 in Corpus Christi; certified TXDOT/DBE/HUB firm offering boundary, topographic, ALTA/ACSM title, and pipeline route surveys across Texas.",
    "websiteUrl": "http://www.texasgeotech.com"
  },
  {
    "recordId": "REC-UT-01",
    "firstName": "Mark",
    "lastName": "Nickel",
    "companyName": "Flint Land Surveying & Development",
    "position": "Principal & Estimator",
    "email": "mark@flintutah.com",
    "phone": "(801) 716-0448",
    "stateRegion": "Utah",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Based in West Jordan; over 20 years in operation; provides construction surveying, development layout, boundary surveys, and subdivision platting in Utah.",
    "websiteUrl": "https://flintlandsurveying.com"
  },
  {
    "recordId": "REC-VT-01",
    "firstName": "Ryan",
    "lastName": "Downey",
    "companyName": "Point of Beginning Inc.",
    "position": "Owner & Licensed Land Surveyor",
    "email": "rdowney@vermontlandsurveying.com",
    "phone": "(802) 362-7322",
    "stateRegion": "Vermont",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Veteran-owned firm in Dorset, VT; founded in 2014; provides boundary surveying, ALTA/NSPS title surveys, topographic mapping, and septic/subdivision design.",
    "websiteUrl": "https://vermontlandsurveying.com"
  },
  {
    "recordId": "REC-VA-01",
    "firstName": "Larry",
    "lastName": "Ogle",
    "companyName": "Larry T. Ogle, Sr., L.S., L.C.",
    "position": "Owner & Licensed Land Surveyor",
    "email": "larrysr@surveyingland.net",
    "phone": "(540) 797-8220",
    "stateRegion": "Virginia",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Based in Salem; over 50 years experience in surveying; provides ALTA/NSPS surveys, FEMA elevation certificates, boundary, and subdivision surveys in Roanoke area.",
    "websiteUrl": "https://surveyingland.net"
  },
  {
    "recordId": "REC-WA-01",
    "firstName": "Brian",
    "lastName": "Gullikson",
    "companyName": "NorthLine Surveying, Inc.",
    "position": "Founder & President",
    "email": "BrianG@NorthLineSurveying.com",
    "phone": "(360) 899-9598",
    "stateRegion": "Washington",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Established in 2018; based in Burlington, WA; provides boundary surveys, short plats, construction staking, and topographic surveys in Skagit and surrounding counties.",
    "websiteUrl": "https://northlinesurveying.com"
  },
  {
    "recordId": "REC-WV-01",
    "firstName": "Kenneth",
    "lastName": "Moran",
    "companyName": "Advanced Land Services, Inc.",
    "position": "President & Professional Surveyor",
    "email": "kmoran@prosurvey.com",
    "phone": "(304) 329-3000",
    "stateRegion": "West Virginia",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Based in Kingwood; provides commercial and residential boundary surveys, construction layout, GPS mapping, and oil/gas pipeline surveying across West Virginia.",
    "websiteUrl": "https://prosurvey.com"
  },
  {
    "recordId": "REC-WI-01",
    "firstName": "Dustin",
    "lastName": "Vreeland",
    "companyName": "Vreeland Land Surveyors & Engineers",
    "position": "Principal & Professional Land Surveyor",
    "email": "dustin@vreelandassociates.us",
    "phone": "(715) 241-0947",
    "stateRegion": "Wisconsin",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Family-owned business based in Weston, WI; specializes in boundary surveys, site design, construction staking, FEMA LOMA certifications, and permitting.",
    "websiteUrl": "https://vreelandlandsurveying.com"
  },
  {
    "recordId": "REC-WY-01",
    "firstName": "Jesse",
    "lastName": "Frisbee",
    "companyName": "Eagle Engineering & Surveying, Inc.",
    "position": "Principal & Licensed Surveyor",
    "email": "jf@eagle-wyo.com",
    "phone": "(307) 347-8276",
    "stateRegion": "Wyoming",
    "leadStatus": "Cold Lead - AI Scraped",
    "associatedNote": "Based in Worland, WY; provides boundary surveys, engineering surveying, water rights surveys, topographic mapping, and subdivision design across Wyoming.",
    "websiteUrl": "https://eagle-wyo.com"
  }
];

module.exports = { agent2Data };
